import Image
import numpy as np

def imgToBW(img, threshold, image=False):
	width, height = img.size
	imgBW = np.asarray(img.convert("L"))

	result = np.ones((height, width), dtype=np.uint8)

	for row in range(height):
		for col in range(width):
			if imgBW[row][col] > threshold:
				result[row][col] = 0xFF
			else:
				result[row][col] = 0x00
	if image:
		return Image.fromarray(result)
	return result

actualManas = [0, 0, 1, 1, 1, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 3, 3,
               3, 3, 3, 3, 4, 4, 4, 4,
               5, 5, 5, 6, 6, 6, 6, 6,
               7, 7, 8, 9,
               0, 1, 1, 1, 1, 1, 1, 1,
               1, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               3, 3, 3, 3, 3, 3, 3, 4,
               4, 4, 4, 5, 5, 5, 5, 6,
               7, 9,
               1, 1, 1, 1, 1, 1, 1, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 4, 4,
               4, 4, 4, 4, 4, 4, 5, 5,
               5, 6, 6, 7,
               1, 1, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 1, 1, 1, 1, 1,
               2, 2, 2, 2, 2, 2, 3, 3,
               4, 4, 4, 4, 4, 5, 5, 5,
               3, 3, 3, 3, 3, 4, 4, 4,
               5, 5, 6, 7,
               0, 0, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 1, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 3, 3,
               3, 3, 3, 3, 4, 4, 4, 4,
               7, 10,
               4, 4, 4, 5, 5, 5, 6, 6,
               1, 2, 2, 2, 2, 2, 2, 2,
               0, 0, 1, 1, 1, 1, 1, 1,
               2, 2, 2, 2, 2, 2, 2, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 4, 4, 4, 4, 5, 5, 5,
               5, 5, 5, 6, 6, 7,
               0, 0, 0, 1, 1, 1, 1, 1,
               1, 1, 1, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 3, 3,
               4, 5, 5, 5, 6,
               3, 3, 3, 3, 3, 4, 4, 4,
               0, 0, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 3, 3, 3, 3,
               3, 3, 3, 4, 4, 4, 4, 4,
               4, 4, 5, 5, 5, 6, 6, 6,
               6, 6, 7, 9,
               0, 1, 1, 1, 1, 2, 2, 2,
               2, 3, 3, 3, 3, 3, 3, 3,
               2, 2, 2, 2, 2, 2, 2, 2,
               3, 4, 4, 4, 4, 4, 4, 5,
               5, 6, 6, 6, 7, 7, 7,
               0, 0, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 1, 1, 1, 1, 1,
               1, 1, 1, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               2, 2, 2, 2, 2, 2, 2, 2,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 3, 3,
               3, 3, 3, 3, 3, 3, 4, 4,
               4, 4, 4, 4, 4, 4, 4, 4,
               4, 4, 4, 4, 4, 4, 4, 4,
               4, 4, 4, 4, 4, 4, 4, 4,
               4, 4, 4, 4, 4, 4, 4, 4,
               4, 4, 4, 5, 5, 5, 5, 5,
               5, 5, 5, 5, 5, 5, 5, 5,
               5, 5, 5, 5, 5, 5, 5, 5,
               5, 5, 6, 6, 6, 6, 6, 6,
               5, 5, 5, 5, 5, 5, 5, 5,
               6, 6, 6, 6, 6, 6, 6, 6,
               6, 6, 7, 7, 7, 7, 7, 8,
               8, 8, 9, 9, 9, 20]
actualTypes = ["Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion", "Spell",  "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Minion",
               "Spell",  "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Spell",  "Minion",
               "Minion", "Minion", "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion",
               "Minion", "Weapon", "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion",
               "Weapon", "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Spell",
               "Minion", "Minion", "Minion", "Spell",  "Minion", "Minion", "Minion", "Minion",
               "Weapon", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Spell",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Minion", "Minion", "Spell",  "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Minion", "Minion", "Spell",  "Spell",
               "Minion", "Spell",  "Spell",  "Spell",
               "Weapon", "Weapon", "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Weapon", "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Minion", "Spell",  "Spell",  "Minion",
               "Spell",  "Spell",  "Minion", "Minion", "Minion", "Weapon", "Spell",  "Spell",
               "Minion", "Minion", "Spell",  "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Minion", "Minion", "Minion", "Minion", "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Minion", "Spell",  "Spell",  "Spell",  "Minion",
               "Minion", "Spell",
               "Minion", "Minion", "Minion", "Spell",  "Spell",  "Minion", "Spell",  "Minion",
               "Minion", "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion",
               "Minion", "Minion", "Minion", "Minion", "Minion", "Minion", "Minion", "Weapon",
               "Weapon", "Weapon", "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion",
               "Minion", "Spell",  "Spell",  "Minion", "Minion", "Weapon", "Weapon", "Spell",
               "Minion", "Minion", "Minion", "Spell",  "Spell",  "Spell",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",
               "Minion", "Minion", "Minion", "Weapon", "Spell",  "Spell",  "Spell",  "Spell",
               "Spell",  "Minion", "Minion", "Minion", "Minion", "Minion", "Weapon", "Spell",
               "Minion", "Spell",  "Minion", "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion", "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion",
               "Minion", "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Spell",  "Minion",
               "Minion", "Minion", "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Spell",
               "Minion", "Minion", "Minion", "Spell",  "Spell",  "Spell",  "Minion", "Minion",
               "Minion", "Minion", "Minion", "Minion", "Minion", "Spell",  "Minion", "Minion",
               "Minion", "Minion", "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Weapon", "Spell",  "Spell",
               "Minion", "Weapon", "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion",
               "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Spell",  "Minion", "Minion",
               "Minion", "Weapon", "Spell",  "Minion", "Minion", "Minion", "Minion", "Weapon",
               "Minion", "Minion", "Minion", "Minion", "Weapon", "Spell",  "Minion"]



goldenMinions = [12, 107, 150, 157, 200, 208, 225, 227, 263, 274, 331, 343, 370, 412, 417, 423, 479, 492, 501, 505]

#Only first 3 classes because lazy
rarities = [ "Free",   "Free",   "Free",   "Free",   "Common", "Free",   "Free",   "Common",
             "Free",   "Free",   "Common", "Common", "Common", "Common", "Free",   "Free",  
             "Common", "Free",   "Common", "Common", "Free",   "Free",   "Common", "Free",  
             "Rare",   "Common", "Common", "Epic",   "Rare",   "Rare",   "Free",   "Rare",
             "Epic",   "Epic",   "Free",   "Rare",
             "Free",   "Free",   "Free",   "Free",   "Free",   "Common", "Free",   "Free",  
             "Common", "Common", "Common", "Rare",   "Rare",   "Common", "Epic",   "Rare",
             "Rare",   "Common", "Common", "Epic",   "Common", "Common", "Common", "Epic",
             "Rare",   "Free",   "Common", "Free",   "Rare",   "Common", "Rare",   "Free",  
             "Rare",   "Free",   "Free",   "Common", "Rare",   "Common", "Common", "Rare",
             "Epic",   "Legendary",
             "Epic",   "Free",   "Free",   "Common", "Free",   "Free",   "Common", "Free",  
             "Free",   "Common", "Free",   "Free",   "Rare",   "Rare",   "Common", "Common",
             "Free",   "Free",   "Rare",   "Common", "Common", "Free",   "Free",   "Common",
             "Common", "Rare",   "Rare",   "Rare",   "Rare",   "Rare",   "Common", "Epic",
             "Free",   "Free",   "Common", "Rare",   "Rare",   "Free",   "Common", "Common",
             "Free",   "Rare",   "Rare",   "Common"]
frees   = len([x for x in rarities if x == "Free"])
commons = len([x for x in rarities if x == "Common"])
rares   = len([x for x in rarities if x == "Rare"])
epics   = len([x for x in rarities if x == "Epic"])
legendaries = 1